#!/bin/sh
SERVICE_NAME="sushilja.in"
SERVICE_API_SIGNUP="http://api.sushilja.in/sushiljain/sh/signup/index.php"
echo "...............welcome to signup @$SERVICE_NAME............... "


printf "what is your email?  -> "
read E_MAIL
# parse input to be valid, accept or re-ask
echo "recorded as $E_MAIL."


printf "set your password?  -> "
read PASSWD
# parse input to be valid, accept or re-ask

printf "confirm password?  -> "
read PASSWD2
# parse input to be valid, accept or re-ask
# check for both passwd to be equal, accept or re-ask
echo "$PASSWD2, "
echo "password saved, remember it."


# post request to signup api.
curl -X POST -F 'u_email=$E_MAIL' -F 'u_passwd=$PASSWD2' $SERVICE_API_SIGNUP
echo "Account created."


# verification mail sent


printf "what is your name?  -> "
read NAME
echo "recorded as $NAME."
echo "Hello, $NAME.  Nice to meet you."


# echo "Hello, $E_MAIL.  Nice to meet you."
# echo "Hello, $E_MAIL.  Nice to meet you."